Use abseil logging in allocd_utils
This was missed in https://github.com/google/android-cuttlefish/pull/1955 .

Changing the log header additionally caused a new unrelated error, which
is also fixed:
```
In file included from allocd/alloc_utils.cpp:16:
allocd/alloc_utils.h:28:10: error: module //allocd:alloc_utils does not depend on a module exporting 'cuttlefish/common/libs/fs/shared_fd.h'
   28 | #include "cuttlefish/common/libs/fs/shared_fd.h"
      |          ^
1 error generated.
```

Bug: b/321795781