Move stamp_helper.sh into base directory.
- Having `stamp_helper.sh` out of the base directory breaks building the
  package when using the base directory only.

- git clone https://github.com/google/android-cuttlefish -b v1.2.0 \
&& dpkg-source -b android-cuttlefish/base/ \
&& rm -rf android-cuttlefish \
&& dpkg-source -x cuttlefish-common_1.2.0.dsc \
&& cd cuttlefish-common-1.2.0 \
&& debuild -uc -us

```
ERROR: <builtin>: BazelWorkspaceStatusAction stable-status.txt failed: Failed to determine workspace status: Process exited with status 127
/bin/sh: 1: ../../tools/buildutils/stamp_helper.sh: not found
INFO: Elapsed time: 12.224s, Critical Path: 0.03s
INFO: 1 process: 1 internal.
ERROR: Build did NOT complete successfully
FAILED:
make[1]: *** [debian/rules:25: override_dh_auto_build] Error 1
make[1]: Leaving directory '/home/sorama/cuttlefish-common-1.2.0'
make: *** [debian/rules:17: build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui failed
```

- b/407077605