Don't use stdout and stderr as variables
stdout and stderr are keywords that should not be used as variables.
Musl libc defines them as macros, which causes build failures:
device/google/cuttlefish/host/commands/cvd/unittests/server/cmd_runner.cpp:55:15: error: parentheses were disambiguated as redundant parentheses around declaration of variable named 'stdout' [-Werror,-Wvexing-parse]
  std::string stdout;
              ^~~~~~
external/musl/include/stdio.h:67:16: note: expanded from macro 'stdout'
               ^~~~~~~~

Test: builds
Change-Id: I0c0bb7557c010313bc255190f3333193a08db471