Explicitly choose a rust toolchain version
Initially reported by @cjreynol, we are seeing build errors in CI:
```
[15,710 / 22,568] Compiling Rust rlib uuid v1.27.0 (23 files); 0s local, disk-cache ... (4 actions, 1 running)
  ERROR: /root/.cache/bazel/_bazel_root/86add146dd382dd24750dce66e8a10be/external/rules_rust++crate+vhost_user_media_workspace_crates__uuid-1.27.0/BUILD.bazel:23:13: Compiling Rust rlib uuid v1.27.0 (23 files) failed: (Exit 1): process_wrapper failed: error executing Rustc command (from target @@rules_rust++crate+vhost_user_media_workspace_crates__uuid-1.27.0//:uuid) bazel-out/k8-opt-exec-ST-d57f47055a04/bin/external/rules_rust+/util/process_wrapper/process_wrapper --env-file ... (remaining 56 arguments skipped)
  error: `core::slice::ascii::<impl [u8]>::eq_ignore_ascii_case` is not yet stable as a const fn
     --> external/rules_rust++crate+vhost_user_media_workspace_crates__uuid-1.27.0/src/parser.rs:159:16
```

`uuid` [requires rust
1.89.0](https://github.com/uuid-rs/uuid/blob/b62154e8be41ce42127cba08ee5e5cef3e2ea971/Cargo.toml#L31)
so maybe we are choosing an older version? I am not sure from the
`rules_rust` source code what it chooses as a default.

In this change, we explicitly pin on rust 1.99, the latest stable.
Netsim requires syntax edition 2021 and everything else seems to build
with that, so we use that for now.

Bug: b/568932900