Fake out KeymasterContext::GenerateAttestation.
Implementation that signs the certificate with a TPM-resident key is
still TODO.

Still fails a CTS test with:
STACKTRACE:
java.lang.Exception: Failed on curve 0 challenge 0 purpose 0 includeValidityDates true and devicePropertiesAttestation true
        at android.keystore.cts.KeyAttestationTest.testEcAttestation(KeyAttestationTest.java:181)
...
Caused by: java.lang.AssertionError: Attestations must not contain any extra data
Expected: is an empty collection
     but: <[2.5.29.35, 2.5.29.15]>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at android.keystore.cts.KeyAttestationTest.checkUnexpectedOids(KeyAttestationTest.java:711)

This looks like it is another instance of b/158212234 and b/149746301.

Bug: 155695501
Test: Treehugger
Change-Id: I2ad89beeae8ede46d31b3591d22bef4e5a732def