Increase userdata size to 4.25GB
Fixes x86 CtsHardwareTestCases
android.hardware.cts.LowRamDeviceTest#testMinDataPartitionSize

java.lang.AssertionError: Application data partition size does
not meet requirement. Found = 4160421888, Minimum = 4294967296

This occurs because the usable space must be above 4GB, not the raw
partition size.

Fixes: 124520809
Change-Id: I3c6ae0875f72c8c8c318f3ff194835e7fbd291f3