Fix compile error for clang update.
device/google/cuttlefish/guest/hals/hwcomposer/common/stats_keeper.h:216:43:
error: cannot initialize a parameter of type 'cvd::CompositionStats *' with
an rvalue of type 'cvd::CompositionStats **'
    stats_keeper_.GetLastCompositionStats(&stats);
                                          ^~~~~~
device/google/cuttlefish/guest/hals/hwcomposer/common/stats_keeper.h:97:50:
note: passing argument to parameter 'stats_p' here
  void GetLastCompositionStats(CompositionStats* stats_p);

Bug: 149839606
Test: build.

Change-Id: Ic7b775749ed5b43d2baa5fcf43bdf435e2ace564
Merged-In: Ic7b775749ed5b43d2baa5fcf43bdf435e2ace564
(cherry picked from commit 7652ea839d4dcfcb26177259040af0bb27a74829)